### ISSUE TITLE
cannot import name '__version__' from 'marker.settings' 

### ISSUE THREAD

**Issue by fahdmirza** [agi-dude/chainlit-rag#1]
I am trying to install it and while running loader.py, getting following:

(chainlit_rag) Ubuntu@0041-kci-prxmx10005:~/chainlit-rag$ python loader.py -c -n
Traceback (most recent call last):
  File "/home/Ubuntu/chainlit-rag/loader.py", line 9, in <module>
    from marker.convert import convert_single_pdf
  File "/home/Ubuntu/miniconda3/envs/chainlit_rag/lib/python3.11/site-packages/marker/__init__.py", line 16, in <module>
    from .settings import __version__
ImportError: cannot import name '__version__' from 'marker.settings' (/home/Ubuntu/miniconda3/envs/chainlit_rag/lib/python3.11/site-packages/marker/settings.py)

**Comment by umar-mq** [comment]
Try reinstalling marker and graphrag:

```bash
$ pip install --force-reinstall --no-cache marker-pdf graphrag
```

**Comment by fahdmirza** [comment]
Tried that but same error:


Traceback (most recent call last):
  File "/home/Ubuntu/chainlit-rag/loader.py", line 9, in <module>
    from marker.convert import convert_single_pdf
  File "/home/Ubuntu/miniconda3/envs/chainlit_rag/lib/python3.11/site-packages/marker/__init__.py", line 16, in <module>
    from .settings import __version__
ImportError: cannot import name '__version__' from 'marker.settings' (/home/Ubuntu/miniconda3/envs/chainlit_rag/lib/python3.11/site-packages/marker/settings.py)
(chainlit_rag) Ubuntu@0041-kci-prxmx10005:~/chainlit-rag$

**Comment by jonmach** [comment]
Same issue for me - I also tried to reinstall but it didn't resolve

**Comment by umar-mq** [comment]
This seems to be an error with [marker](https://github.com/VikParuchuri/marker). You should open an issue there

**Comment by jonmach** [comment]
You're right.  Not a chainlit issue - I should have paid more attention to the repo - sorry.  The issue though was with me.  Trashing my entire pip library and reinstalling libraries to avoid long-standing conflicts seemed to resolve it.
